// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file VecMsg.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace { char dummy; }
#endif

#include "VecMsg.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

VecMsg::VecMsg()
{
    // m_index com.eprosima.idl.parser.typecode.PrimitiveTypeCode@7e0e6aa2
    m_index = 0;
    // m_data com.eprosima.idl.parser.typecode.SequenceTypeCode@4fb64261


}

VecMsg::~VecMsg()
{


}

VecMsg::VecMsg(const VecMsg &x)
{
    m_index = x.m_index;
    m_data = x.m_data;
}

VecMsg::VecMsg(VecMsg &&x)
{
    m_index = x.m_index;
    m_data = std::move(x.m_data);
}

VecMsg& VecMsg::operator=(const VecMsg &x)
{

    m_index = x.m_index;
    m_data = x.m_data;

    return *this;
}

VecMsg& VecMsg::operator=(VecMsg &&x)
{

    m_index = x.m_index;
    m_data = std::move(x.m_data);

    return *this;
}

size_t VecMsg::getMaxCdrSerializedSize(size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    current_alignment += (100 * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);

    current_alignment = 2100000; //TODO > 2MB


    return current_alignment - initial_alignment;
}

size_t VecMsg::getCdrSerializedSize(const VecMsg& data, size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);

    if (data.data().size() > 0)
    {
        current_alignment += (data.data().size() * 1) + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);
    }




    return current_alignment - initial_alignment;
}

void VecMsg::serialize(eprosima::fastcdr::Cdr &scdr) const
{

    scdr << m_index;
    scdr << m_data;
}

void VecMsg::deserialize(eprosima::fastcdr::Cdr &dcdr)
{

    dcdr >> m_index;
    dcdr >> m_data;
}

/*!
 * @brief This function sets a value in member index
 * @param _index New value for member index
 */
void VecMsg::index(uint32_t _index)
{
m_index = _index;
}

/*!
 * @brief This function returns the value of member index
 * @return Value of member index
 */
uint32_t VecMsg::index() const
{
    return m_index;
}

/*!
 * @brief This function returns a reference to member index
 * @return Reference to member index
 */
uint32_t& VecMsg::index()
{
    return m_index;
}

/*!
 * @brief This function copies the value in member data
 * @param _data New value to be copied in member data
 */
void VecMsg::data(const std::vector<uint8_t> &_data)
{
m_data = _data;
}

/*!
 * @brief This function moves the value in member data
 * @param _data New value to be moved in member data
 */
void VecMsg::data(std::vector<uint8_t> &&_data)
{
m_data = std::move(_data);
}

/*!
 * @brief This function returns a constant reference to member data
 * @return Constant reference to member data
 */
const std::vector<uint8_t>& VecMsg::data() const
{
    return m_data;
}

/*!
 * @brief This function returns a reference to member data
 * @return Reference to member data
 */
std::vector<uint8_t>& VecMsg::data()
{
    return m_data;
}

size_t VecMsg::getKeyMaxCdrSerializedSize(size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool VecMsg::isKeyDefined()
{
   return false;
}

void VecMsg::serializeKey(eprosima::fastcdr::Cdr &scdr) const
{
    (void) scdr;
     
     
}
